[package]
name = "rust_ws_gameserver"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
tokio = {version = "1.47.1", features = ["full"]}
tokio-tungstenite = "0.27.0"
tungstenite = "0.27.0"
